frontend/urls.py
from django.urls import path
from . import views

app_name = 'frontend'
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('login/', views.user_login, name='user_login'),
    path('signup/', views.user_signup, name='user_signup'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('edit-password/', views.edit_password, name='edit_password'),
    path('family-tree/', views.family_tree_view, name='family_tree_view'),
    path('update-member/<int:member_id>', views.edit_member, name='edit_member'),
    path('add-member/', views.add_member, name='add_member'),
    path('authenticate/', views.authenticate, name='authenticate'),
]

pedigree_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('frontend.urls')),
]

frontend/models.py
from django.db import models

# Create your models here.

frontend/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.conf import settings

import os
import requests

api_url = os.getenv('API_URL')
client_id = os.getenv('CLIENT_ID')
client_secret = os.getenv('CLIENT_SECRET')

def homepage(response):
	context = {}
	return render(response, 'frontend/homepage.html', context)

def user_login(response):
	context = {}
	return render(response, 'frontend/login.html', context)

def authenticate(response):
	username = response.POST.get('username')
	password = response.POST.get('password')
	token_request = generate_token(username, password)
	return HttpResponse(token_request.get('access_token'))

def user_signup(response):
	context = {}
	return render(response, 'frontend/signup.html', context)

def edit_profile(response):
	context = {}
	return render(response, 'frontend/edit_profile.html', context)

def edit_password(response):
	context = {}
	return render(response, 'frontend/edit_password.html', context)

def family_tree_view(response):
	context = {}
	return render(response, 'frontend/family_tree_view.html', context)

def edit_member(response, member_id):
	context = {'member_id': member_id}
	return render(response, 'frontend/edit_member.html', context)

def add_member(response):
	context = {}
	return render(response, 'frontend/add_member.html', context)

def generate_token(username, password):
	url = "{}/o/token/".format(api_url)
	payload = {
		'grant_type': 'password',
		'username': username,
		'password': password
	}

	auth = (client_id, client_secret)
	resource = requests.post(url, data=payload, auth=auth)
	resource_data = resource.json()

	return resource_data

frontend/templates/frontend/add_member.html
{% extends 'frontend/main.html' %}
{% load static %}

{% block content %}

    <h1>Add family member</h1>

    <div class="input-field">
        <label for="relation">Relation</label><br>
        <select id="relation" name="relation" form="create-member-form" required>
            <option value="Father">Father</option>
            <option value="Mother">Mother</option>
            <option value="Brother">Brother</option>
            <option value="Sister">Sister</option>
            <option value="Son">Son</option>
            <option value="Daughter">Daughter</option>
            <option value="Grandfather">Grandfather</option>
            <option value="Grandmother">Grandmother</option>
            <option value="Granddaughter">Granddaughter</option>
            <option value="Grandson">Grandson</option>
            <option value="Aunt">Aunt</option>
            <option value="Uncle">Uncle</option>
        </select>
    </div>

    <form id='create-member-form' method='POST'>

        <div class="input-field">
            <label for="first_name">First Name</label><br>
            <input type="text" name="first_name" id="first-name" required>
        </div>

        <div class="input-field">
            <label for="last_name">Last Name</label><br>
            <input type="text" name="last_name" id="last-name" required>
        </div>

        <div class="input-field">
            <label for="birthday">Birthday</label><br>
            <input type="date" name="birthday" id="birthday" required>
        </div>

        <div class="input-field">
            <label for="vital_status">Vital status</label><br>
            <input type="text" name="vital_status" id="vital-status" required>
        </div>

        <div class="input-field">
            <label for="is_in_law">Is in law</label><br>
            <input type="checkbox" name="is_in_law" id="is-in-law">
        </div>

        <input type="submit" value="Add" />
    </form>

{% endblock %}

{% block scripts %}
    <script src="{% static 'frontend/addMember.js' %}"></script>
{% endblock %}

frontend/templates/frontend/edit_member.html
{% extends 'frontend/main.html' %}
{% load static %}

{% block content %}

    <h1>Edit member</h1>

    <div class="input-field">
        <label for="relation">Relation</label><br>
        <select id="relation" name="relation" form="update-member-form" required>
            <option value="Father">Father</option>
            <option value="Mother">Mother</option>
            <option value="Brother">Brother</option>
            <option value="Sister">Sister</option>
            <option value="Son">Son</option>
            <option value="Daughter">Daughter</option>
            <option value="Grandfather">Grandfather</option>
            <option value="Grandmother">Grandmother</option>
            <option value="Granddaughter">Granddaughter</option>
            <option value="Grandson">Grandson</option>
            <option value="Aunt">Aunt</option>
            <option value="Uncle">Uncle</option>
        </select>
    </div>

    <form id='update-member-form' method='POST'>

        <div class="input-field">
            <label for="first_name">First Name</label><br>
            <input type="text" name="first_name" id="first-name" required>
        </div>

        <div class="input-field">
            <label for="last_name">Last Name</label><br>
            <input type="text" name="last_name" id="last-name" required>
        </div>

        <div class="input-field">
            <label for="birthday">Birthday</label><br>
            <input type="date" name="birthday" id="birthday" required>
        </div>

        <div class="input-field">
            <label for="vital_status">Vital status</label><br>
            <input type="text" name="vital_status" id="vital-status" required>
        </div>

        <div class="input-field">
            <label for="is_in_law">Is in law</label><br>
            <input type="checkbox" name="is_in_law" id="is-in-law">
        </div>

        <input type="hidden" name="member_id" id="member-id" value="{{member_id}}"> 
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

{% block scripts %}
    <script src="{% static 'frontend/editMember.js' %}"></script>
{% endblock %}

frontend/templates/frontend/edit_password.html
{% extends 'frontend/main.html' %}
{% load static %}

{% block content %}

    <form id='change-password-form' method="POST">
        {% csrf_token %}

        <div class="input-field">
            <label for="old_password">Enter you current password: </label><br>
            <input type="password" name="old_password" id="change-password-old-password" required>
        </div>

        <div class="input-field">
            <label for="password1">New password: </label><br>
            <input type="password" name="password1" id="change-password-password1" required>
        </div>

        <div class="input-field">
            <label for="password2">Re-type new password: </label><br>
            <input type="password" name="password2" id="change-password-password2" required>
        </div>

        <br><input type="submit" value="Submit">
    </form>

{% endblock %}

{% block scripts %}
    <script src="{% static 'frontend/profile.js' %}"></script>
{% endblock %}

frontend/templates/frontend/edit_profile.html
{% extends 'frontend/main.html' %}
{% load static %}

{% block content %}

    <form id='profile-form' method="POST">
        {% csrf_token %}

        <div class="input-field">
            <label for="first_name">First Name</label><br>
            <input type="text" name="first_name" id="profile-first-name" required>
        </div>

        <div class="input-field">
            <label for="last_name">Last Name</label><br>
            <input type="text" name="last_name" id="profile-last-name" required>
        </div>
        
        <div class="input-field">
            <label for="email">Email</label><br>
            <input type="email" name="email" id="profile-email" required>
        </div>

        <div class="input-field">
            <label for="birthday">Birthday</label><br>
            <input type="date" name="birthday" id="profile-birthday" required>
        </div>

        <div class="input-field">
            <label for="vital_status">Vital Status</label><br>
            <input type="text" name="vital_status" id="profile-vital-status" required>
        </div>

        <br><input type="submit" value="Submit">
    </form>
    <br>

    <a href="{% url 'frontend:edit_password' %}">Change password</a>

{% endblock %}

{% block scripts %}
    <script src="{% static 'frontend/profile.js' %}"></script>
{% endblock %}

frontend/templates/frontend/family_tree_view.html
{% extends 'frontend/main.html' %}
{% load static %}

{% block content %}

    <h1>Family Tree</h1>

    <a href="{% url 'frontend:add_member' %}">Add member</a>

    <table id="family-member-table">
        <tr>
            <th>Relation</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Birthday</th>
            <th>Vital Status</th>
            <th>Actions</th>
        </tr>
        <tr>
            <td>You</td>
            <td id="user-first-name"></td>
            <td id="user-last-name"></td>
            <td id="user-birthday"></td>
            <td id="user-vital-status"></td>
            <td>
                <form action="{% url 'frontend:edit_profile' %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="Edit"/>
                </form>
            </td>
        </tr>
    </table>

{% endblock %}

{% block scripts %}
    <script src="{% static 'frontend/familyTree.js' %}"></script>
{% endblock %}

frontend/templates/frontend/homepage.html
{% extends 'frontend/main.html' %}
{% load static %}

{% block content %}

	<div id="user-homepage" hidden>
		<h1>Welcome! <span id="user-welcome"></span></h1>
		<a href="{% url 'frontend:edit_profile' %}">Edit profile</a><br>
		<a href="{% url 'frontend:family_tree_view' %}">Family Tree</a><br>
		<button class="logout-button">Logout</button>
	</div>

	<div id="no-user-homepage" hidden>
		<h1>No user logged in</h1>
		<a href="{% url 'frontend:user_signup' %}">Sign-Up</a><br>
		<a href="{% url 'frontend:user_login' %}">Sign-In</a><br><br>
	</div>


{% endblock %}

{% block scripts %}
    <script src="{% static 'frontend/homepage.js' %}"></script>
{% endblock %}

frontend/templates/frontend/login.html
{% extends 'frontend/main.html' %}
{% load static %}

{% block content %}

    <form id='user-login-form' method="POST">
        {% csrf_token %}
        <label for="username">Username</label><br>
        <input type="text" name="username" id="login_username" required><br>

        <label for="password">Password</label><br>
        <input type="password" name="password" id="login_password" required><br><br>
        <input type="submit" value="Login">
    </form>

{% endblock %}

{% block scripts %}
    <script src="{% static 'frontend/login.js' %}"></script>
{% endblock %}

frontend/templates/frontend/main.html
{% load static %}
<!DOCTYPE html>
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="{% static 'frontend/main.js' %}"></script>
  <link rel="stylesheet" href="{% static 'frontend/main.css' %}">

</head>
<html>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>
<script>
  const apiEndpoint = '{{ api_endpoint }}'
</script>
{% block scripts %}
{% endblock %}

frontend/templates/frontend/signup.html
{% extends 'frontend/main.html' %}
{% load static %}

{% block content %}

    <form id='signup-form' method="POST">
        {% csrf_token %}
        <div class="input-field">
            <label for="username">Username</label><br>
            <input type="text" name="username" id="signup-username" required>
        </div>

        <div class="input-field">
            <label for="first_name">First Name</label><br>
            <input type="text" name="first_name" id="signup-first-name" required>
        </div>

        <div class="input-field">
            <label for="last_name">Last Name</label><br>
            <input type="text" name="last_name" id="signup-last-name" required>
        </div>
        
        <div class="input-field">
            <label for="email">Email</label><br>
            <input type="email" name="email" id="signup-email" required>
        </div>

        <div class="input-field">
            <label for="birthday">Birthday</label><br>
            <input type="date" name="birthday" id="signup-birthday" required>
        </div>

        <div class="input-field">
            <label for="vital_status">Vital Status</label><br>
            <input type="text" name="vital_status" id="signup-vital-status" required>
        </div>

        <div class="input-field">
            <label for="password1">Password</label><br>
            <input type="password" name="password1" id="signup-password1" required>
        </div>
        
        <div class="input-field">
            <label for="password2">Re-type Password</label><br>
            <input type="password" name="password2" id="signup-password2" required>
        </div>

        <br><input type="submit" value="Register">
    </form>

{% endblock %}

{% block scripts %}
    <script src="{% static 'frontend/signup.js' %}"></script>
{% endblock %}